### ISSUE TITLE
Structue value!

### ISSUE THREAD

**Issue by rbinmo1** [HydrologicEngineeringCenter/NSI#10]
Whether it is depreciated replacement cost, replacement cost, market value?

**Comment by GitLutz** [comment]
NSI structure values represent depreciated replacement value.  The methodology is somewhat simple though, where we start with estimated replacement cost and then depreciate it by 1% for every year after the structure was built for 20 years and then assume it stays there after that.  So it will never be less then 80% of the replacement cost.

**Comment by rbinmo1** [comment]
Is the content cost calculate  in similar way? I mean depreciated replacement cost or just replacement cost or value only!

**Comment by GitLutz** [comment]
Content value is estimated based on an assumed structure to content value ratio; implicitly, this is also depreciated replacement value.  However, single family residential structures (RES1-XXXX) assume content value is equal to structure value despite a more accurate estimate being closer to 50%.  This is done because depth-damage curves (Economic Guidance Memorandum curves) traditionally used by USACE in software such as HEC-FDA and HEC-LifeSim assume the higher ratio and a lower depth-damage relationship (maxing out near 40% damage).  If a NSI user is not using these EGM curves, they should make a new assumption on the content to structure value relationship for RES1 structures.
